services:
  postgres:
    image: postgres:latest
    container_name: filestorage-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filestorage_db
    ports:
      - "5432:5432"

